version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "todo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
